"""Write detection results out as TSV, JSON, and a self-contained HTML report."""
from __future__ import annotations

import csv
import json
from pathlib import Path

from .consensus import ConsensusCall

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>AMR Consensus Report - {sample_name}</title>
<style>
  :root {{
    --high: #1a7f37; --medium: #9a6700; --low: #cf222e; --bg: #f6f8fa; --border: #d0d7de;
  }}
  body {{ font-family: -apple-system, Segoe UI, Helvetica, Arial, sans-serif; margin: 0; padding: 2rem;
          background: #ffffff; color: #1f2328; }}
  h1 {{ font-size: 1.5rem; margin-bottom: 0.25rem; }}
  .subtitle {{ color: #656d76; margin-bottom: 1.5rem; }}
  .summary {{ display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }}
  .card {{ background: var(--bg); border: 1px solid var(--border); border-radius: 8px;
           padding: 1rem 1.25rem; min-width: 140px; }}
  .card .n {{ font-size: 1.6rem; font-weight: 700; }}
  .card .label {{ color: #656d76; font-size: 0.85rem; }}
  table {{ border-collapse: collapse; width: 100%; font-size: 0.9rem; }}
  th, td {{ border: 1px solid var(--border); padding: 0.5rem 0.7rem; text-align: left; }}
  th {{ background: var(--bg); position: sticky; top: 0; }}
  tr:hover {{ background: #f6f8fa; }}
  .badge {{ display: inline-block; padding: 0.15rem 0.5rem; border-radius: 999px;
            font-size: 0.75rem; font-weight: 600; color: white; }}
  .badge.high {{ background: var(--high); }}
  .badge.medium {{ background: var(--medium); }}
  .badge.low {{ background: var(--low); }}
  .dbs {{ font-family: monospace; font-size: 0.8rem; color: #656d76; }}
  footer {{ margin-top: 2rem; color: #656d76; font-size: 0.8rem; }}
</style>
</head>
<body>
  <h1>AMR Gene Detection &mdash; Consensus Report</h1>
  <div class="subtitle">Sample: <strong>{sample_name}</strong> &nbsp;|&nbsp; Databases queried: {databases} &nbsp;|&nbsp; Generated by amr-consensus</div>

  <div class="summary">
    <div class="card"><div class="n">{n_calls}</div><div class="label">Resistance loci</div></div>
    <div class="card"><div class="n">{n_high}</div><div class="label">High confidence</div></div>
    <div class="card"><div class="n">{n_drug_classes}</div><div class="label">Drug classes implicated</div></div>
    <div class="card"><div class="n">{n_contigs}</div><div class="label">Contigs with hits</div></div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Contig</th><th>Locus</th><th>Gene(s)</th><th>Confidence</th>
        <th>Best identity</th><th>Coverage</th><th>Databases</th><th>Drug classes</th>
      </tr>
    </thead>
    <tbody>
      {rows}
    </tbody>
  </table>

  <footer>
    Reference sequences sourced from ResFinder / CARD / NCBI AMRFinderPlus / ARG-ANNOT / MEGARes
    (via the ABRicate database mirror). Thresholds: identity &ge; {min_id}%, coverage &ge; {min_cov}%.
  </footer>
</body>
</html>
"""

ROW_TEMPLATE = """<tr>
  <td>{contig}</td>
  <td>{locus_start}-{locus_end}</td>
  <td><strong>{genes}</strong></td>
  <td><span class="badge {confidence}">{confidence}</span> {score}</td>
  <td>{identity}%</td>
  <td>{coverage}%</td>
  <td class="dbs">{dbs}</td>
  <td>{drugs}</td>
</tr>"""


def write_reports(
    calls: list[ConsensusCall],
    outdir: Path,
    sample_name: str,
    databases: list[str],
    min_identity: float,
    min_coverage: float,
) -> dict[str, Path]:
    outdir.mkdir(parents=True, exist_ok=True)
    paths = {
        "tsv": outdir / "amr_consensus_report.tsv",
        "json": outdir / "amr_consensus_report.json",
        "html": outdir / "amr_consensus_report.html",
    }

    _write_tsv(calls, paths["tsv"])
    _write_json(calls, paths["json"], sample_name, databases, min_identity, min_coverage)
    _write_html(calls, paths["html"], sample_name, databases, min_identity, min_coverage)
    return paths


def _write_tsv(calls: list[ConsensusCall], path: Path) -> None:
    fieldnames = [
        "contig", "locus_start", "locus_end", "primary_gene", "n_allele_variants",
        "gene_names", "supporting_databases",
        "n_databases", "best_identity", "mean_identity", "best_coverage",
        "drugs", "confidence_score", "confidence",
    ]
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        for c in calls:
            writer.writerow(c.to_dict())


def _write_json(
    calls: list[ConsensusCall], path: Path, sample_name: str,
    databases: list[str], min_identity: float, min_coverage: float,
) -> None:
    payload = {
        "sample": sample_name,
        "databases_queried": databases,
        "thresholds": {"min_identity": min_identity, "min_coverage": min_coverage},
        "n_loci": len(calls),
        "calls": [c.to_dict() for c in calls],
    }
    with open(path, "w") as f:
        json.dump(payload, f, indent=2)


def _write_html(
    calls: list[ConsensusCall], path: Path, sample_name: str,
    databases: list[str], min_identity: float, min_coverage: float,
) -> None:
    rows = "\n".join(
        ROW_TEMPLATE.format(
            contig=c.contig,
            locus_start=c.locus_start,
            locus_end=c.locus_end,
            genes=c.primary_gene + (f" (+{c.n_allele_variants - 1} allele variants)" if c.n_allele_variants > 1 else ""),
            confidence=c.confidence,
            score=c.confidence_score,
            identity=c.best_identity,
            coverage=c.best_coverage,
            dbs=";".join(sorted(set(c.supporting_databases))),
            drugs=";".join(sorted(set(c.drugs))) or "-",
        )
        for c in calls
    ) or "<tr><td colspan='8'>No resistance genes detected above thresholds.</td></tr>"

    drug_classes = {d for c in calls for d in c.drugs if d}
    contigs = {c.contig for c in calls}
    n_high = sum(1 for c in calls if c.confidence == "high")

    html = HTML_TEMPLATE.format(
        sample_name=sample_name,
        databases=", ".join(databases),
        n_calls=len(calls),
        n_high=n_high,
        n_drug_classes=len(drug_classes),
        n_contigs=len(contigs),
        rows=rows,
        min_id=min_identity,
        min_cov=min_coverage,
    )
    with open(path, "w") as f:
        f.write(html)
